/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryList: typeof import('./components/themes/CategoryList.vue')['default']
    CxDarkLightMode: typeof import('./components/CxDarkLightMode.vue')['default']
    CxLanguageDialog: typeof import('./components/CxLanguageDialog.vue')['default']
    CxLineChartCard: typeof import('./components/CxLineChartCard.vue')['default']
    CxLoginDialog: typeof import('./components/CxLoginDialog.vue')['default']
    CxPopoverMenu: typeof import('./components/CxPopoverMenu.vue')['default']
    CxSearchDialog: typeof import('./components/CxSearchDialog.vue')['default']
    CxXButton: typeof import('./components/login/CxXButton.vue')['default']
    Hero: typeof import('./components/home/Hero.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./components/themes/Theme.vue')['default']
    ThemeCard: typeof import('./components/themes/ThemeCard.vue')['default']
  }
}
