/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CxDarkLightMode: typeof import('./components/CxDarkLightMode.vue')['default']
    CxLanguageDialog: typeof import('./components/CxLanguageDialog.vue')['default']
    CxLoginDialog: typeof import('./components/CxLoginDialog.vue')['default']
    CxPopoverMenu: typeof import('./components/CxPopoverMenu.vue')['default']
    CxSearchDialog: typeof import('./components/CxSearchDialog.vue')['default']
    CxXButton: typeof import('./components/login/CxXButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
