/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayerContent: typeof import('./components/entry/AudioPlayerContent.vue')['default']
    AudioPlayerDialog: typeof import('./components/entry/AudioPlayerDialog.vue')['default']
    AvatarFrame: typeof import('./components/media/AvatarFrame.vue')['default']
    CategoryList: typeof import('./components/themes/CategoryList.vue')['default']
    CollectionCard: typeof import('./components/collection/CollectionCard.vue')['default']
    CollectionFooter: typeof import('./components/collection/CollectionFooter.vue')['default']
    CollectionMedia: typeof import('./components/collection/media/CollectionMedia.vue')['default']
    CxDarkLightMode: typeof import('./components/CxDarkLightMode.vue')['default']
    CxDeposit: typeof import('./components/wallet/CxDeposit.vue')['default']
    CxHistory: typeof import('./components/wallet/CxHistory.vue')['default']
    CxLanguageDialog: typeof import('./components/CxLanguageDialog.vue')['default']
    CxLineChartCard: typeof import('./components/CxLineChartCard.vue')['default']
    CxLoginDialog: typeof import('./components/CxLoginDialog.vue')['default']
    CxPopoverMenu: typeof import('./components/CxPopoverMenu.vue')['default']
    CxSearchDialog: typeof import('./components/CxSearchDialog.vue')['default']
    CxXButton: typeof import('./components/login/CxXButton.vue')['default']
    EntryCard: typeof import('./components/entry/EntryCard.vue')['default']
    EntryCardMockGrid: typeof import('./components/entry/EntryCardMockGrid.vue')['default']
    EntryCardMockGridDebug: typeof import('./components/entry/EntryCardMockGridDebug.vue')['default']
    EntryCardSkeleton: typeof import('./components/entry/EntryCardSkeleton.vue')['default']
    EntryFooter: typeof import('./components/entry/EntryFooter.vue')['default']
    EntryMediaAudio: typeof import('./components/entry/media/EntryMediaAudio.vue')['default']
    EntryMediaEntry: typeof import('./components/entry/media/EntryMediaEntry.vue')['default']
    EntryMediaImage: typeof import('./components/entry/media/EntryMediaImage.vue')['default']
    EntryMediaVideo: typeof import('./components/entry/media/EntryMediaVideo.vue')['default']
    Hero: typeof import('./components/home/Hero.vue')['default']
    MediaFrame: typeof import('./components/media/MediaFrame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./components/themes/Theme.vue')['default']
    ThemeCard: typeof import('./components/themes/ThemeCard.vue')['default']
  }
}
