/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/[username]': RouteRecordInfo<'/[username]', '/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/Account': RouteRecordInfo<'/Account', '/Account', Record<never, never>, Record<never, never>>,
    '/Community': RouteRecordInfo<'/Community', '/Community', Record<never, never>, Record<never, never>>,
    '/Ecosystem': RouteRecordInfo<'/Ecosystem', '/Ecosystem', Record<never, never>, Record<never, never>>,
    '/Explore': RouteRecordInfo<'/Explore', '/Explore', Record<never, never>, Record<never, never>>,
    '/Fan': RouteRecordInfo<'/Fan', '/Fan', Record<never, never>, Record<never, never>>,
    '/Favorites': RouteRecordInfo<'/Favorites', '/Favorites', Record<never, never>, Record<never, never>>,
    '/Featured': RouteRecordInfo<'/Featured', '/Featured', Record<never, never>, Record<never, never>>,
    '/feed/[...path]': RouteRecordInfo<'/feed/[...path]', '/feed/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/FirstSteps': RouteRecordInfo<'/FirstSteps', '/FirstSteps', Record<never, never>, Record<never, never>>,
    '/Purchased': RouteRecordInfo<'/Purchased', '/Purchased', Record<never, never>, Record<never, never>>,
    '/section/[...path]': RouteRecordInfo<'/section/[...path]', '/section/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/VideoUpload': RouteRecordInfo<'/VideoUpload', '/VideoUpload', Record<never, never>, Record<never, never>>,
    '/WaitList': RouteRecordInfo<'/WaitList', '/WaitList', Record<never, never>, Record<never, never>>,
    '/WaitListStats': RouteRecordInfo<'/WaitListStats', '/WaitListStats', Record<never, never>, Record<never, never>>,
    '/Wallet': RouteRecordInfo<'/Wallet', '/Wallet', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...catchAll].vue': {
      routes: '/[...catchAll]'
      views: never
    }
    'src/pages/[username].vue': {
      routes: '/[username]'
      views: never
    }
    'src/pages/Account.vue': {
      routes: '/Account'
      views: never
    }
    'src/pages/Community.vue': {
      routes: '/Community'
      views: never
    }
    'src/pages/Ecosystem.vue': {
      routes: '/Ecosystem'
      views: never
    }
    'src/pages/Explore.vue': {
      routes: '/Explore'
      views: never
    }
    'src/pages/Fan.vue': {
      routes: '/Fan'
      views: never
    }
    'src/pages/Favorites.vue': {
      routes: '/Favorites'
      views: never
    }
    'src/pages/Featured.vue': {
      routes: '/Featured'
      views: never
    }
    'src/pages/feed/[...path].vue': {
      routes: '/feed/[...path]'
      views: never
    }
    'src/pages/FirstSteps.vue': {
      routes: '/FirstSteps'
      views: never
    }
    'src/pages/Purchased.vue': {
      routes: '/Purchased'
      views: never
    }
    'src/pages/section/[...path].vue': {
      routes: '/section/[...path]'
      views: never
    }
    'src/pages/VideoUpload.vue': {
      routes: '/VideoUpload'
      views: never
    }
    'src/pages/WaitList.vue': {
      routes: '/WaitList'
      views: never
    }
    'src/pages/WaitListStats.vue': {
      routes: '/WaitListStats'
      views: never
    }
    'src/pages/Wallet.vue': {
      routes: '/Wallet'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
