/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/[username]': RouteRecordInfo<'/[username]', '/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/Account': RouteRecordInfo<'/Account', '/account', Record<never, never>, Record<never, never>>,
    '/Banned': RouteRecordInfo<'/Banned', '/banned', Record<never, never>, Record<never, never>>,
    '/collection/[id]': RouteRecordInfo<'/collection/[id]', '/collection/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/CreateCollection': RouteRecordInfo<'/CreateCollection', '/create-collection', Record<never, never>, Record<never, never>>,
    '/CreatorStudio': RouteRecordInfo<'/CreatorStudio', '/creator-studio', Record<never, never>, Record<never, never>>,
    '/SalesHistory': RouteRecordInfo<'/SalesHistory', '/creator-studio/sales', Record<never, never>, Record<never, never>>,
    '/SubscribersList': RouteRecordInfo<'/SubscribersList', '/creator-studio/subscribers', Record<never, never>, Record<never, never>>,
    '/Explore': RouteRecordInfo<'/Explore', '/explore', Record<never, never>, Record<never, never>>,
    '/f/[slug]': RouteRecordInfo<'/f/[slug]', '/f/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/Favorites': RouteRecordInfo<'/Favorites', '/favorites', Record<never, never>, Record<never, never>>,
    '/Featured': RouteRecordInfo<'/Featured', '/featured', Record<never, never>, Record<never, never>>,
    '/feed/[...path]': RouteRecordInfo<'/feed/[...path]', '/feed/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/Guidelines': RouteRecordInfo<'/Guidelines', '/guidelines', Record<never, never>, Record<never, never>>,
    '/listen/[id]': RouteRecordInfo<'/listen/[id]', '/listen/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/listen/AudioRecommendationsList': RouteRecordInfo<'/listen/AudioRecommendationsList', '/listen/AudioRecommendationsList', Record<never, never>, Record<never, never>>,
    '/MyFranchise': RouteRecordInfo<'/MyFranchise', '/my-franchise', Record<never, never>, Record<never, never>>,
    'AuthXCallback': RouteRecordInfo<'AuthXCallback', '/oauth2/callback', Record<never, never>, Record<never, never>>,
    '/preview/[id]': RouteRecordInfo<'/preview/[id]', '/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Privacy': RouteRecordInfo<'/Privacy', '/privacy', Record<never, never>, Record<never, never>>,
    '/Purchased': RouteRecordInfo<'/Purchased', '/purchased', Record<never, never>, Record<never, never>>,
    '/read/[id]': RouteRecordInfo<'/read/[id]', '/read/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/read/ReadRecommendationsList': RouteRecordInfo<'/read/ReadRecommendationsList', '/read/ReadRecommendationsList', Record<never, never>, Record<never, never>>,
    '/Results': RouteRecordInfo<'/Results', '/results', Record<never, never>, Record<never, never>>,
    '/section/[...path]': RouteRecordInfo<'/section/[...path]', '/section/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/spaces/[spaceId]': RouteRecordInfo<'/spaces/[spaceId]', '/spaces/:spaceId', { spaceId: ParamValue<true> }, { spaceId: ParamValue<false> }>,
    '/subscriptions': RouteRecordInfo<'/subscriptions', '/subscriptions', Record<never, never>, Record<never, never>>,
    '/Terms': RouteRecordInfo<'/Terms', '/terms', Record<never, never>, Record<never, never>>,
    '/themes': RouteRecordInfo<'/themes', '/themes', Record<never, never>, Record<never, never>>,
    '/VideoUpload': RouteRecordInfo<'/VideoUpload', '/upload', Record<never, never>, Record<never, never>>,
    '/view/[id]': RouteRecordInfo<'/view/[id]', '/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/view/ImageRecommendationsList': RouteRecordInfo<'/view/ImageRecommendationsList', '/view/ImageRecommendationsList', Record<never, never>, Record<never, never>>,
    '/WaitList': RouteRecordInfo<'/WaitList', '/waitlist', Record<never, never>, Record<never, never>>,
    '/WaitListStats': RouteRecordInfo<'/WaitListStats', '/waitlist/stats', Record<never, never>, Record<never, never>>,
    '/Wallet': RouteRecordInfo<'/Wallet', '/wallet', Record<never, never>, Record<never, never>>,
    '/watch/[id]': RouteRecordInfo<'/watch/[id]', '/watch/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/watch/RecommendationsList': RouteRecordInfo<'/watch/RecommendationsList', '/watch/RecommendationsList', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...catchAll].vue': {
      routes: '/[...catchAll]'
      views: never
    }
    'src/pages/[username].vue': {
      routes: '/[username]'
      views: never
    }
    'src/pages/Account.vue': {
      routes: '/Account'
      views: never
    }
    'src/pages/Banned.vue': {
      routes: '/Banned'
      views: never
    }
    'src/pages/collection/[id].vue': {
      routes: '/collection/[id]'
      views: never
    }
    'src/pages/CreateCollection.vue': {
      routes: '/CreateCollection'
      views: never
    }
    'src/pages/CreatorStudio.vue': {
      routes: '/CreatorStudio'
      views: never
    }
    'src/pages/SalesHistory.vue': {
      routes: '/SalesHistory'
      views: never
    }
    'src/pages/SubscribersList.vue': {
      routes: '/SubscribersList'
      views: never
    }
    'src/pages/Explore.vue': {
      routes: '/Explore'
      views: never
    }
    'src/pages/f/[slug].vue': {
      routes: '/f/[slug]'
      views: never
    }
    'src/pages/Favorites.vue': {
      routes: '/Favorites'
      views: never
    }
    'src/pages/Featured.vue': {
      routes: '/Featured'
      views: never
    }
    'src/pages/feed/[...path].vue': {
      routes: '/feed/[...path]'
      views: never
    }
    'src/pages/Guidelines.vue': {
      routes: '/Guidelines'
      views: never
    }
    'src/pages/listen/[id].vue': {
      routes: '/listen/[id]'
      views: never
    }
    'src/pages/listen/AudioRecommendationsList.vue': {
      routes: '/listen/AudioRecommendationsList'
      views: never
    }
    'src/pages/MyFranchise.vue': {
      routes: '/MyFranchise'
      views: never
    }
    'src/pages/oauth2/callback.vue': {
      routes: 'AuthXCallback'
      views: never
    }
    'src/pages/preview/[id].vue': {
      routes: '/preview/[id]'
      views: never
    }
    'src/pages/Privacy.vue': {
      routes: '/Privacy'
      views: never
    }
    'src/pages/Purchased.vue': {
      routes: '/Purchased'
      views: never
    }
    'src/pages/read/[id].vue': {
      routes: '/read/[id]'
      views: never
    }
    'src/pages/read/ReadRecommendationsList.vue': {
      routes: '/read/ReadRecommendationsList'
      views: never
    }
    'src/pages/Results.vue': {
      routes: '/Results'
      views: never
    }
    'src/pages/section/[...path].vue': {
      routes: '/section/[...path]'
      views: never
    }
    'src/pages/spaces/[spaceId].vue': {
      routes: '/spaces/[spaceId]'
      views: never
    }
    'src/pages/subscriptions.vue': {
      routes: '/subscriptions'
      views: never
    }
    'src/pages/Terms.vue': {
      routes: '/Terms'
      views: never
    }
    'src/pages/themes.vue': {
      routes: '/themes'
      views: never
    }
    'src/pages/VideoUpload.vue': {
      routes: '/VideoUpload'
      views: never
    }
    'src/pages/view/[id].vue': {
      routes: '/view/[id]'
      views: never
    }
    'src/pages/view/ImageRecommendationsList.vue': {
      routes: '/view/ImageRecommendationsList'
      views: never
    }
    'src/pages/WaitList.vue': {
      routes: '/WaitList'
      views: never
    }
    'src/pages/WaitListStats.vue': {
      routes: '/WaitListStats'
      views: never
    }
    'src/pages/Wallet.vue': {
      routes: '/Wallet'
      views: never
    }
    'src/pages/watch/[id].vue': {
      routes: '/watch/[id]'
      views: never
    }
    'src/pages/watch/RecommendationsList.vue': {
      routes: '/watch/RecommendationsList'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
